--drop table MYSCHEMA.SPRING_TEST;
CREATE TABLE MYSCHEMA.SPRING_TEST(
    ID INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) primary key,
    TEXT VARCHAR(100)
)

GRANT ALL ON MYSCHEMA.SPRING_TEST TO MYUSER